########################################
# Pipeline
########################################
image: electronuserland/electron-builder:wine

cache:
  untracked: true
  paths:
    - node_modules
    - build

variables:
  BUILD_NUMBER: $CI_BUILD_ID

stages:
  - build
  - test
  - publish

########################################
# Jobs
########################################
build:
  stage: build
  script:
    - yarn install --pure-lockfile
    - yarn run build:prod

lint:
  stage: test
  script:
    - yarn run lint

dist:win:
  stage: publish
  script:
    - yarn run dist -- --linux --win
  artifacts:
    paths:
      - dist
  only:
    - tags
