########################################
# Pipeline
########################################
image: electronuserland/electron-builder:wine

cache:
  untracked: true
  paths:
    - node_modules
    - build

variables:
  BUILD_NUMBER: $CI_BUILD_ID

stages:
  - build
  - test
  - prepublish
  - publish

########################################
# Jobs
########################################
build:
  stage: build
  script:
    - yarn install --pure-lockfile
    - yarn run build:test

test:
  stage: test
  script:
    - yarn run test:unit

e2e:
  stage: test
  script:
    - yarn run test:e2e

lint:
  stage: test
  script:
    - yarn run lint

build:prod:
  stage: prepublish
  script:
    - yarn run build:prod

dist:
  stage: publish
  script:
    - yarn run dist -- --linux --win --publish never
  artifacts:
    paths:
      - dist
  only:
    - tags
