########################################
# Templates
########################################
.test: &test
  stage: test
  before_script:
    - Xvfb -ac -screen scrn 1280x2000x24 :9.0 &
    - export DISPLAY=:9.0
########################################
# Pipeline
########################################
image: electronuserland/electron-builder:wine

cache:
  untracked: true
  paths:
    - node_modules
    - build

variables:
  BUILD_NUMBER: $CI_BUILD_ID
  SPECTRON_TIMEOUT: 10000

stages:
  - build
  - test
  - prepublish
  - publish
########################################
# Jobs
########################################
build:
  stage: build
  script:
    - yarn install --pure-lockfile
    - yarn run build:test

test:
  <<: *test
  script:
    - yarn run test:unit

e2e:
  <<: *test
  script:
    - yarn run test:e2e

lint:
  stage: test
  script:
    - yarn run lint

dist:
  stage: publish
  script:
    - yarn run build:prod
    - yarn run dist -- --linux --win --publish never
  artifacts:
    paths:
      - dist
  only:
    - tags
