sudo: false

osx_image: xcode8.3

language: node_js

node_js: "7"

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xvfb

env:
  global:
    - ELECTRON_CACHE="$HOME/.cache/electron"
    - ELECTRON_BUILDER_CACHE="$HOME/.cache/electron-builder"
    - SPECTRON_TIMEOUT=10000

cache:
  yarn: true
  directories:
    - node_modules
    - build
    - $ELECTRON_CACHE
    - $ELECTRON_BUILDER_CACHE

before_script:
  - Xvfb -ac -screen scrn 1280x2000x24 :99 > /dev/null 2>&1 &
  - export DISPLAY=":99.0"

install:
  - yarn install --pure-lockfile

script:
  - yarn build:test
  - yarn run test
  - yarn run lint
  - yarn build:prod
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      yarn run publish -- --linux;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      yarn run publish -- --mac --win;
    fi

before_cache:
  - rm -rf "$ELECTRON_BUILDER_CACHE/wine"
